#define MUSIC_TITLE 35
#define MUSIC_P1 36
#define MUSIC_P2 37
#define MUSIC_P3 38
#define MUSIC_P4 39
#define MUSIC_EPICWIN 40
#define MUSIC_FINAL 41
#define MUSIC_LETSPLAY 42
#define MUSIC_LOSE 43
#define MUSIC_WIN 44
#define MUSIC_TIMEOUT 45
#define MUSIC_AWAIT 46
#define MUSIC_AUDIENCE 47

#define MODEL_VEIL 0xFC
#define MODEL_DYNTEXT 0xFE